//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRQ.SI.SCB.UI.Web.UserControls {
    
    
    public partial class MessageBox {
        
        /// <summary>
        /// AlertBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BRQ.SI.SCB.UI.Web.UserControls.MessageBoxTypes.AlertBox AlertBox1;
        
        /// <summary>
        /// ErrorBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BRQ.SI.SCB.UI.Web.UserControls.MessageBoxTypes.ErrorBox ErrorBox1;
        
        /// <summary>
        /// InformationBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BRQ.SI.SCB.UI.Web.UserControls.MessageBoxTypes.InformationBox InformationBox1;
        
        /// <summary>
        /// QuestionBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BRQ.SI.SCB.UI.Web.UserControls.MessageBoxTypes.QuestionBox QuestionBox1;
        
        /// <summary>
        /// SuccessBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BRQ.SI.SCB.UI.Web.UserControls.MessageBoxTypes.SuccessBox SuccessBox1;
    }
}
